import type {
  Account,
  AppSettings,
  DashboardData,
  Inbound,
  LogEntry,
} from "./types"

// Demo data is only used as a fallback when the local backend API is not
// reachable (e.g. inside the web preview). In the packaged app the real
// endpoints under /api/* are used instead.

export const demoDashboard: DashboardData = {
  replyEnabled: false,
  scanCompleted: true,
  hasLoggedInAccount: true,
  scanState: "done",
  todayInbound: 30,
  pendingCards: 3,
  sentCards: 5,
  failedCards: 1,
  runningAccounts: 2,
  errorAccounts: 0,
  needReview: 2,
  qualified: 22,
  activity: {
    backgroundScan: "2 个账号正在后台扫描最近 7 天私信",
    cardTask: "回复未开启，待发卡队列中有 3 位客户等待发送名片",
    errorAccount: "暂无异常账号",
    lastAction: "客资识别完成：小红薯62E6515D 咨询吞咽异响",
  },
}

export const demoInbounds: Inbound[] = [
  {
    id: "1",
    platform: "xhs",
    accountName: "张湘民官方账号",
    customerName: "小红薯62E6515D",
    disease: "吞咽异响",
    phone: "138****6620",
    summary: "咨询吞咽异响，想了解检查方式",
    status: "pending",
    failReason: "",
  },
  {
    id: "2",
    platform: "xhs",
    accountName: "张湘民官方账号",
    customerName: "爱笑的小鹿",
    disease: "UPPP术",
    phone: "150****3388",
    summary: "询问UPPP手术费用",
    status: "sent",
    sentAt: "2026-07-13 10:24",
  },
  {
    id: "3",
    platform: "xhs",
    accountName: "耳鼻喉李医生",
    customerName: "夜跑的风",
    disease: "鼾症",
    phone: "",
    summary: "描述夜间打鼾严重，咨询是否需手术",
    status: "review",
  },
  {
    id: "4",
    platform: "xhs",
    accountName: "张湘民官方账号",
    customerName: "海边的贝壳",
    disease: "预约咨询",
    phone: "137****9012",
    summary: "留下手机号预约咨询",
    status: "sending",
  },
  {
    id: "5",
    platform: "xhs",
    accountName: "耳鼻喉李医生",
    customerName: "微光",
    disease: "咽鼓管异常开放",
    phone: "189****2211",
    summary: "咨询咽鼓管异常开放治疗",
    status: "failed",
    failReason: "会话窗口未找到发送按钮，已重试 3 次",
  },
  {
    id: "6",
    platform: "xhs",
    accountName: "张湘民官方账号",
    customerName: "清风徐来",
    disease: "费用咨询",
    phone: "",
    summary: "咨询腭帆张肌松解术大概费用",
    status: "not_qualified",
  },
  {
    id: "7",
    platform: "xhs",
    accountName: "耳鼻喉李医生",
    customerName: "阿橙",
    disease: "咽鼓管置管术",
    phone: "133****7788",
    summary: "术后咨询恢复情况",
    status: "sent",
    sentAt: "2026-07-13 09:12",
  },
  {
    id: "8",
    platform: "xhs",
    accountName: "张湘民官方账号",
    customerName: "小满",
    disease: "改良UPPP术（局麻）",
    phone: "158****4455",
    summary: "咨询改良UPPP局麻手术",
    status: "pending",
  },
]

export const demoAccounts: Account[] = [
  {
    index: 0,
    name: "张湘民官方账号",
    platform: "xhs",
    lastAction: "名片发送成功：爱笑的小鹿",
    loginState: "logged_in",
    scanState: "scanning",
    todayInbound: 18,
    pendingCards: 2,
    todaySent: 4,
  },
  {
    index: 1,
    name: "耳鼻喉李医生",
    platform: "xhs",
    lastAction: "扫描到新私信：微光",
    loginState: "logged_in",
    scanState: "scanning",
    todayInbound: 12,
    pendingCards: 1,
    todaySent: 1,
  },
  {
    index: 2,
    name: "睡眠健康科普",
    platform: "xhs",
    lastAction: "登录失效，需要扫码",
    loginState: "logged_out",
    scanState: "idle",
    todayInbound: 0,
    pendingCards: 0,
    todaySent: 0,
  },
]

export const demoLogs: LogEntry[] = [
  {
    id: "l1",
    time: "2026-07-13 10:24:31",
    level: "success",
    event: "名片发送成功",
    account: "张湘民官方账号",
    detail: "已向 爱笑的小鹿 发送商家名片",
  },
  {
    id: "l2",
    time: "2026-07-13 10:23:58",
    level: "info",
    event: "加入待发卡",
    account: "张湘民官方账号",
    detail: "客户 海边的贝壳 已识别，加入待发卡队列",
  },
  {
    id: "l3",
    time: "2026-07-13 10:22:10",
    level: "info",
    event: "客资识别完成",
    account: "耳鼻喉李医生",
    detail: "微光 识别为 咽鼓管异常开放",
  },
  {
    id: "l4",
    time: "2026-07-13 10:20:45",
    level: "info",
    event: "扫描到新私信",
    account: "耳鼻喉李医生",
    detail: "发现 3 条最近 7 天新私信",
  },
  {
    id: "l5",
    time: "2026-07-13 10:18:02",
    level: "error",
    event: "发卡失败",
    account: "耳鼻喉李医生",
    detail: "微光：会话窗口未找到发送按钮，已重试 3 次",
  },
  {
    id: "l6",
    time: "2026-07-13 09:50:12",
    level: "warn",
    event: "登录失效，需要扫码",
    account: "睡眠健康科普",
    detail: "登录态已过期，请到账号页重新扫码登录",
  },
  {
    id: "l7",
    time: "2026-07-13 09:30:00",
    level: "info",
    event: "账号暂停扫描",
    account: "睡眠健康科普",
    detail: "连续失败自动暂停扫描",
  },
]

export const demoSettings: AppSettings = {
  autoScanOnStart: true,
  trayOnStart: true,
  autoLaunch: false,
  ai: {
    keyConfigured: true,
    model: "gpt-4o-mini",
    baseUrl: "https://api.openai.com/v1",
  },
  pace: {
    maxPerRound: 1,
    intervalMin: 5,
    intervalMax: 15,
    autoPauseOnFail: true,
  },
}
